-- CreateTable
CREATE TABLE "Profile" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "travelers" TEXT NOT NULL,
    "vacationStyle" TEXT NOT NULL DEFAULT '[]',
    "travelPace" TEXT NOT NULL DEFAULT 'moderate',
    "flightClass" TEXT NOT NULL DEFAULT 'economy',
    "maxLayovers" INTEGER NOT NULL DEFAULT 1,
    "health" TEXT NOT NULL DEFAULT '{}',
    "accommodation" TEXT NOT NULL DEFAULT '{}',
    "passports" TEXT NOT NULL DEFAULT '[]',
    "existingVisas" TEXT NOT NULL DEFAULT '[]',
    "existingETAs" TEXT NOT NULL DEFAULT '[]',
    "hasIsraeliStamps" BOOLEAN NOT NULL DEFAULT false,
    "criminalRecord" BOOLEAN NOT NULL DEFAULT false,
    "travelInsurance" BOOLEAN NOT NULL DEFAULT false,
    "budgetTotal" REAL,
    "budgetCurrency" TEXT NOT NULL DEFAULT 'EUR',
    "budgetBreakdown" TEXT,
    "cuisinePreferences" TEXT NOT NULL DEFAULT '[]',
    "languagesSpoken" TEXT NOT NULL DEFAULT '[]',
    "loyaltyPrograms" TEXT NOT NULL DEFAULT '[]',
    "visitedCountries" TEXT NOT NULL DEFAULT '[]',
    "favoriteDestinations" TEXT NOT NULL DEFAULT '[]',
    "minorsTraveling" TEXT,
    "preferredAirlines" TEXT NOT NULL DEFAULT '[]',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Trip" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "profileId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "originCity" TEXT NOT NULL,
    "originCode" TEXT NOT NULL,
    "destinations" TEXT NOT NULL DEFAULT '[]',
    "startDate" DATETIME NOT NULL,
    "endDate" DATETIME NOT NULL,
    "datesFlexible" BOOLEAN NOT NULL DEFAULT false,
    "visaRequirements" TEXT,
    "vaccinationReqs" TEXT,
    "entryRestrictions" TEXT,
    "selectedRoute" TEXT,
    "selectedAccommodations" TEXT,
    "selectedCarRental" TEXT,
    "aiRecommendations" TEXT,
    "estimatedTotal" REAL,
    "status" TEXT NOT NULL DEFAULT 'planning',
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Trip_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "MockFlight" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "fromCode" TEXT NOT NULL,
    "fromCity" TEXT NOT NULL,
    "fromCountry" TEXT NOT NULL,
    "toCode" TEXT NOT NULL,
    "toCity" TEXT NOT NULL,
    "toCountry" TEXT NOT NULL,
    "airline" TEXT NOT NULL,
    "flightNumber" TEXT NOT NULL,
    "departureTime" TEXT NOT NULL,
    "arrivalTime" TEXT NOT NULL,
    "durationMin" INTEGER NOT NULL,
    "stops" INTEGER NOT NULL DEFAULT 0,
    "layoverCode" TEXT,
    "layoverCity" TEXT,
    "layoverCountry" TEXT,
    "layoverMin" INTEGER,
    "transitVisa" BOOLEAN NOT NULL DEFAULT false,
    "priceEconomy" REAL NOT NULL,
    "priceBusiness" REAL NOT NULL,
    "priceFirst" REAL NOT NULL,
    "seatsLeft" INTEGER NOT NULL DEFAULT 50,
    "isStopover" BOOLEAN NOT NULL DEFAULT false,
    "stopoverNights" INTEGER
);

-- CreateTable
CREATE TABLE "MockHotel" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "city" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "stars" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "pricePerNight" REAL NOT NULL,
    "petFriendly" BOOLEAN NOT NULL DEFAULT false,
    "wheelchairAccess" BOOLEAN NOT NULL DEFAULT false,
    "breakfastIncl" BOOLEAN NOT NULL DEFAULT false,
    "parking" BOOLEAN NOT NULL DEFAULT false,
    "pool" BOOLEAN NOT NULL DEFAULT false,
    "gym" BOOLEAN NOT NULL DEFAULT false,
    "wifi" BOOLEAN NOT NULL DEFAULT true,
    "distanceCenter" REAL NOT NULL,
    "rating" REAL NOT NULL,
    "reviewCount" INTEGER NOT NULL,
    "imageSlug" TEXT NOT NULL,
    "address" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "MockCar" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "city" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "company" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "seats" INTEGER NOT NULL,
    "automatic" BOOLEAN NOT NULL DEFAULT true,
    "pricePerDay" REAL NOT NULL,
    "crossBorderAllowed" BOOLEAN NOT NULL DEFAULT true,
    "crossBorderFee" REAL NOT NULL DEFAULT 0,
    "unlimitedMiles" BOOLEAN NOT NULL DEFAULT true,
    "deposit" REAL NOT NULL,
    "minAge" INTEGER NOT NULL DEFAULT 21,
    "airportPickup" BOOLEAN NOT NULL DEFAULT true,
    "imageSlug" TEXT NOT NULL
);
